name: "word cloud"
on:
  schedule:
    - cron: "0 * * * *" #毎時0分に実行

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2

      - name: Create dot env file
        shell: bash
        run: |
          touch .env
          echo "CK=${{ secrets.CK }}" >> .env
          echo "CS=${{ secrets.CS }}" >> .env
          echo "AT=${{ secrets.AT }}" >> .env
          echo "AS=${{ secrets.AS }}" >> .env
          echo "BT=${{ secrets.BT }}" >> .env

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
          python -m unidic download

      - name: Run bot.py
        run: |
          python ./bot.py
