name: "wordcloud"
on:
  schedule:
    - cron: "0 2 * * *" # 1日昼12時に1回投稿(JST)

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: Create dot env file
        shell: bash
        run: |
          touch .env
          echo "CK=${{ secrets.CK }}" >> .env
          echo "CS=${{ secrets.CS }}" >> .env
          echo "AT=${{ secrets.AT }}" >> .env
          echo "AS=${{ secrets.AS }}" >> .env
          echo "BT=${{ secrets.BT }}" >> .env

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
          python -m unidic download

      - name: Run bot.py
        run: |
          python ./bot.py
